[package]
name = "spotlight-extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.79"
thiserror = "1.0.56"
spotlight-macros = { git = "https://github.com/rspotlight/macros.git" }
