[package]
name = "blazyr-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
abi_stable = { version = "0.11.3", default-features = false }
# spotlight-macros = { git = "https://github.com/rspotlight/macros.git" }
