[package]
name = "spotlight-extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
abi_stable = { version = "0.10", default-features = false }
# spotlight-macros = { git = "https://github.com/rspotlight/macros.git" }
